name: code_editor_app
description: A code editor app for mobile
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
